import { buildVaultFilename } from './vault';
import { executeMcpTool } from './mcp';
import { writeObsidianNote } from './obsidian-writer';

export type ObsidianNoteInput = {
  readonly title: string;
  readonly markdown: string;
  readonly milestone: string;
  readonly category: string;
  readonly subcategory: string;
  readonly tags: readonly string[];
  readonly now?: Date;
  readonly path?: string;
  readonly noteType?: 'brain-distill' | 'brain-distill-research' | 'brain-distill-link';
  readonly parent?: string;
  readonly children?: readonly string[];
};

export type ObsidianNote = {
  readonly path: string;
  readonly content: string;
};

export type McpToolExecutor = (
  toolName: string,
  args: Record<string, unknown>
) => Promise<unknown>;

const FRONTMATTER_PATTERN = /^---\r?\n[\s\S]*?\r?\n---\r?\n*/;
function normalizeTags(tags: readonly string[]): string[] {
  return Array.from(new Set(
    tags
      .map(tag => tag.trim().replace(/^#+/, ''))
      .filter(Boolean)
  )).slice(0, 8);
}

function stripGeneratedEnvelope(markdown: string, title: string): string {
  const withoutFrontmatter = markdown.replace(FRONTMATTER_PATTERN, '').trim();
  const escapedTitle = title.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return withoutFrontmatter
    .replace(new RegExp(`^#\\s+${escapedTitle}\\s*\\r?\\n+`, 'i'), '')
    .trim();
}

function normalizeMetadataValue(value: string): string {
  return value
    .trim()
    .replace(/^\[\[/, '')
    .replace(/\]\]$/, '')
    .replace(/^#+/, '')
    .trim();
}

function buildLinkList(key: string, links: readonly string[]): string[] {
  return [
    `${key}:`,
    ...links.map(link => `  - ${JSON.stringify(`[[${link}]]`)}`),
  ];
}

function buildTagLines(tags: readonly string[]): string {
  if (tags.length === 0) return '  - "brain-distill"';
  return tags.map(tag => `  - ${JSON.stringify(tag)}`).join('\n');
}

function buildParentLines(parent: string | undefined): string[] {
  if (!parent) return [];
  return [`parent: ${JSON.stringify(`[[${parent}]]`)}`];
}

function buildChildLines(children: readonly string[] | undefined): string[] {
  if (!children) return [];
  if (children.length === 0) return [];
  return buildLinkList('children', children);
}

function getNoteType(input: ObsidianNoteInput): string {
  if (input.noteType) return input.noteType;
  return 'brain-distill';
}

function buildFrontmatter(
  input: ObsidianNoteInput,
  now: Date
): string {
  const tags = normalizeTags(input.tags);

  return [
    '---',
    `type: ${getNoteType(input)}`,
    `created: ${now.toISOString()}`,
    'tags:',
    buildTagLines(tags),
    `milestone: ${JSON.stringify(input.milestone)}`,
    `category: ${JSON.stringify(normalizeMetadataValue(input.category))}`,
    `subcategory: ${JSON.stringify(normalizeMetadataValue(input.subcategory))}`,
    ...buildParentLines(input.parent),
    ...buildChildLines(input.children),
    '---',
  ].join('\n');
}

export function buildObsidianNote(input: ObsidianNoteInput): ObsidianNote {
  const now = input.now ?? new Date();
  const body = stripGeneratedEnvelope(input.markdown, input.title);
  const content = [
    buildFrontmatter(input, now),
    '',
    `# ${input.title}`,
    '',
    body,
    '',
    '---',
    '*Generated by ADHD Brain-Twin Gateway.*',
  ].join('\n');

  return {
    path: input.path ?? buildVaultFilename(input.title, now),
    content,
  };
}

export async function saveToObsidian(
  input: ObsidianNoteInput,
  executeTool: McpToolExecutor = executeMcpTool
): Promise<ObsidianNote> {
  const note = buildObsidianNote(input);
  const result = await writeObsidianNote(note.path, note.content, {
    ...(executeTool === executeMcpTool ? {} : { backend: 'mcp' as const }),
    executeTool,
  });
  console.log(`[obsidian] Saved through ${result.backend.toUpperCase()}: ${note.path}`);
  return note;
}
